### ISSUE TITLE
Appearently some files are Missing in the source code.

### ISSUE THREAD

**Issue by SGQuek** [leedavid/NewGG#1]
to @leedavid 

First and foremost, thank you very much in releasing the source code for a Chinese Chess engine on CPU.

I have gone through your source code and I have tried to compile using VS2019 community. It appears that your source code was created using another version of Visual Studio. I have also read through your announcement at

http://www.ggzero.cn/forum.php?mod=viewthread&tid=274

regarding the code release to the public.

I honestly feel that this work deserves a much wider audience. Firstly because not every computers has GPU with Tensor cores capable of running GGzero. And secondly, many people outside China has not been able to access the QQ portal.

Henceforth I would like to suggest three improvements on the site's features:
1. Kindly mention the type of open source license, say GPL 3.0
2. Kindly provide a compiled exe alongside with the source code.
3. Kindly provide a procedure for us to recompile the source code.

Thank you very much for your kind attention

**Comment by leedavid** [comment]
thank my friend SGQuek.
1. there is no license for this project. u can modifiy this as your think.
2. i will put a release file later soon.
3. i can compile with vs2019 easily, do u have any problem?

**Comment by SGQuek** [comment]
[i can compile with vs2019 easily, do u have any problem?]
Firstly, I admit that I am not into building pure C++ applications through VS. My main expertise is building CUDA application through nvcc.

Thus here is what I have observed of your codes:

1.  on
NewGG-master\I_GGX64\ReadMe.txt
there appears to be a file called
I_GGX64.cpp
but I cannot find that file in the source code that you have uploaded in Github

2. with my limited experience in pure C++ applications through VS, I have tried "rebuilding" through
I_GGX64.vcproj and I_GGX64.vcxproj. here are the errors from my version of VS2019 community.

--------------------------------------------

upon compiling with I_GGX64.vcproj

I_GGX64.vcproj
[Release, x64]

1>------ Rebuild All started: Project: I_GGX64, Configuration: Release x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(36,5): warning MSB4211: The property "IntermediateOutputPath" is being set to a value for the first time, but it was already consumed at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets (35,5)".
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(337,5): warning MSB4211: The property "CleanFile" is being set to a value for the first time, but it was already consumed at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets (35,5)".
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(491,5): warning MSB8028: The intermediate directory (x64\Release\) contains files shared from another project (ST2017_GGX64.vcxproj, ST2017_GGX64_LGL32U_7月-23-105757-2018_Conflict.vcxproj).  This can lead to incorrect clean and rebuild behavior.
1>chess_data.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'chess_data.cpp': No such file or directory
1>main.c
1>c1xx : fatal error C1083: Cannot open source file: 'main.c': No such file or directory
1>my_data.cpp
1>C:\Users\USER\Desktop\New folder\NewGG-master\I_GGX64\my_const.h(56,10): fatal error C1083: Cannot open include file: 'endgame\\²Ð¾Ö¼Ó·Ö_0³µ.h': No such file or directory
1>my_next_mossa_prossimo.c
1>c1xx : fatal error C1083: Cannot open source file: 'my_next_mossa_prossimo.c': No such file or directory
1>util.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'util.cpp': No such file or directory
1>Done building project "I_GGX64.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

I have verified that those file are indeed missing in the source code that you have uploaded in Github

-----------------------------

upon compiling with I_GGX64.vcxproj

1>------ Rebuild All started: Project: I_GGX64, Configuration: Release x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(491,5): warning MSB8028: The intermediate directory (x64\Release\) contains files shared from another project (ST2017_GGX64.vcxproj, ST2017_GGX64_LGL32U_7月-23-105757-2018_Conflict.vcxproj).  This can lead to incorrect clean and rebuild behavior.
1>chess_data.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'chess_data.cpp': No such file or directory
1>main.c
1>c1xx : fatal error C1083: Cannot open source file: 'main.c': No such file or directory
1>my_data.cpp
1>C:\Users\USER\Desktop\New folder\NewGG-master\I_GGX64\my_const.h(56,10): fatal error C1083: Cannot open include file: 'endgame\\²Ð¾Ö¼Ó·Ö_0³µ.h': No such file or directory
1>my_next_mossa_prossimo.c
1>c1xx : fatal error C1083: Cannot open source file: 'my_next_mossa_prossimo.c': No such file or directory
1>util.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'util.cpp': No such file or directory
1>Done building project "I_GGX64.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========


-----------------------------

Moreover, upon opening I_GGX64.vcproj, the following message occurs (kindly refer to the picture)
![G](https://user-images.githubusercontent.com/76813522/103667954-85f28000-4fb1-11eb-878e-37cb02342d46.png)

**Comment by SGQuek** [comment]
Moreover, I am from Malaysia, and hence even our version of OS (Windows 10) may not be all the same. 

Should you willing to ensure the code works even on wider range of platform, I am more than willing to supply more information regarding the version of my OS, and every specific configuration of my VS2019 community at your request.

On the other hand, if it is deemed that I, due to my limited knowledge on VS, had compiled your source code incorrectly, kindly let me know the correct procedure of doing so (which file to access, the correct configuration, the correct compiler to use, etc....) on VS2019 community.

It is also worth informing that some third-party member apparently have worked on your older versions of NewGG prior to the code release, enabling it to utilize a lot of threads. Hence, while you are working on releasing the newest official release file, would that be permissible for me to post that unofficial release in Github too?

Thank you very much for your precious time.

**Comment by leedavid** [comment]
newgg is no need cuda, it only need cpu.

**Comment by leedavid** [comment]
and u can join QQ group 779375937 for discussing more easily. also can download newgg release file in the group

**Comment by SGQuek** [comment]
@leedavid 
FYI, I am from Malaysia, and henceforth I am unable to log in to QQ. I have tried all sorts of methods, which includes submitting my phone number and all sorts of details through
https://ssl.zc.qq.com/v3/index-en.html
Being an overseas phone number to China, it was not recognized by QQ, and therefore I have not been able to join QQ group even till today.

I have also tried to use the mobile app of QQ on my OppoFindX2Pro, but to no avail.

Should you have a way of workaround, kindly let me know.

I will nonetheless be waiting till the release file becomes available on Github.

Thank you for your time and attention.

**Comment by SGQuek** [comment]
@leedavid
In fact, I have done everything mention on the website of
https://chinahow.guide/qq-registration-sign-up/
and it really appears that there is no hope of doing so. 
![Screenshot_2021-01-06-12-09-46-05](https://user-images.githubusercontent.com/76813522/103728904-2aa8a800-501a-11eb-970f-798b53c5be1e.jpg)

If you visit the website, you will see that many people outside of China have faced the same problems in registering to QQ.

Thank you very much for your kind understanding.

**Comment by gaintpd** [comment]
Can you speak Chinese, If you can speak Chinese, you can firstly try to use the QQ international edition client, and then join in the QQ group

**Comment by SGQuek** [comment]
[QQ international edition client]
Tried, not working on my Oppo FindX2Pro bought in Malaysia.

**Comment by gaintpd** [comment]
Please Have a try on the PC end, especially on windows. The problem result in the failure of building the NewGG project seems that the file encoding is not UTF-8.

**Comment by SGQuek** [comment]
@giantpd

FYI, I have tried it many days, and here are the error codes which were previously communicated to the author, @davidlee.

Henceforth I am pretty sure the fesult of the failure is because some files gone missing, as you can see in the error codes generated.

I hereby re-post it here for your kind perusal.

    on
    NewGG-master\I_GGX64\ReadMe.txt
    there appears to be a file called
    I_GGX64.cpp
    but I cannot find that file in the source code that you have uploaded in Github

    with my limited experience in pure C++ applications through VS, I have tried "rebuilding" through
    I_GGX64.vcproj and I_GGX64.vcxproj. here are the errors from my version of VS2019 community.

upon compiling with I_GGX64.vcproj

I_GGX64.vcproj
[Release, x64]

1>------ Rebuild All started: Project: I_GGX64, Configuration: Release x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(36,5): warning MSB4211: The property "IntermediateOutputPath" is being set to a value for the first time, but it was already consumed at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets (35,5)".
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(337,5): warning MSB4211: The property "CleanFile" is being set to a value for the first time, but it was already consumed at "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets (35,5)".
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(491,5): warning MSB8028: The intermediate directory (x64\Release) contains files shared from another project (ST2017_GGX64.vcxproj, ST2017_GGX64_LGL32U_7月-23-105757-2018_Conflict.vcxproj). This can lead to incorrect clean and rebuild behavior.
1>chess_data.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'chess_data.cpp': No such file or directory
1>main.c
1>c1xx : fatal error C1083: Cannot open source file: 'main.c': No such file or directory
1>my_data.cpp
1>C:\Users\USER\Desktop\New folder\NewGG-master\I_GGX64\my_const.h(56,10): fatal error C1083: Cannot open include file: 'endgame\²Ð¾Ö¼Ó·Ö_0³µ.h': No such file or directory
1>my_next_mossa_prossimo.c
1>c1xx : fatal error C1083: Cannot open source file: 'my_next_mossa_prossimo.c': No such file or directory
1>util.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'util.cpp': No such file or directory
1>Done building project "I_GGX64.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

I have verified that those file are indeed missing in the source code that you have uploaded in Github

upon compiling with I_GGX64.vcxproj

1>------ Rebuild All started: Project: I_GGX64, Configuration: Release x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(491,5): warning MSB8028: The intermediate directory (x64\Release) contains files shared from another project (ST2017_GGX64.vcxproj, ST2017_GGX64_LGL32U_7月-23-105757-2018_Conflict.vcxproj). This can lead to incorrect clean and rebuild behavior.
1>chess_data.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'chess_data.cpp': No such file or directory
1>main.c
1>c1xx : fatal error C1083: Cannot open source file: 'main.c': No such file or directory
1>my_data.cpp
1>C:\Users\USER\Desktop\New folder\NewGG-master\I_GGX64\my_const.h(56,10): fatal error C1083: Cannot open include file: 'endgame\²Ð¾Ö¼Ó·Ö_0³µ.h': No such file or directory
1>my_next_mossa_prossimo.c
1>c1xx : fatal error C1083: Cannot open source file: 'my_next_mossa_prossimo.c': No such file or directory
1>util.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'util.cpp': No such file or directory
1>Done building project "I_GGX64.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by SGQuek** [comment]
@giantpd
Thus if there is a way to compile, I believe the project file is neither I_GGX64.vcproj nor I_GGX64.vcxproj, it should be somewhere in the code.

As for the issue of QQ using my MSI_Prestige_14" and Oppo FindX2Pro bought in Malaysia, I am afraid there is not much I can do, because this is something that i have been trying using all methods since last year.

So. I am afraid I will need a dedicated sim card and a dedicated phone tuned to the configuration close to that of China (say Huawei) to do it. But that will take time and money from my side as well.
